ExpenceManagement/Controllers/ExpensesController.cs
using ExpenceManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Collections.Generic;

namespace ExpenceManagement.Controllers
{
    public class ExpensesController : Controller
    {
        ExpensesContext expensesContext = new ExpensesContext();
        public ActionResult Index(string Searchby, string search)
        {
            var expenses = expensesContext.Expenses.Include("Account").Include("Category").ToList();

            if (Searchby == "Details")
            {
                var model = expensesContext.Expenses.Where(exp => exp.Details == search || search == null).ToList();
                return View(model);
            }
            else
            {
                var model = expensesContext.Expenses.Where(exp => exp.Remarks.StartsWith(search) || search == null).ToList();
                return View(model);
            }
            return View(expenses);
        }

        public ActionResult Details(int id)
        {
            Expenses expenses = expensesContext.Expenses.Include("Account").Include("Category").FirstOrDefault(exp => exp.Id == id);
            return View(expenses);
           

        }
        [HttpPost]
        public ActionResult Create(Expenses expenses)
        {
            expensesContext.Expenses.Add(expenses);
            expensesContext.SaveChanges();

            var account = expensesContext.accounts.FirstOrDefault(e => e.Id == expenses.AccountId);
            if(account != null)
            {
                account.Amount = account.Amount - expenses.Amount;
                expensesContext.SaveChanges();
            }
            return Redirect("/Expenses");
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            var categories = expensesContext.Categories.ToList();
            var accounts = expensesContext.accounts.ToList();
            ExpenseModel model = new ExpenseModel()
            {
                Categories = categories,
                Accounts = accounts,
                Expenses = new Expenses()
            };
            return  View(model);
        }


        [HttpPost]
        public ActionResult Edit(Expenses expenses)
        { 
            var old = expensesContext.Expenses.FirstOrDefault(exp => exp.Id == expenses.Id);
            
            var account = expensesContext.accounts.FirstOrDefault(e => e.Id == old.AccountId);
            if (account != null)
            {
                account.Amount = account.Amount + old.Amount - expenses.Amount;
            }
            old.Remarks = expenses.Remarks;
            old.Details = expenses.Details;
            old.Amount = expenses.Amount;
            old.Date = expenses.Date;

            expensesContext.SaveChanges();
            return Redirect("/Expenses");

        }
        [HttpGet]
        public ActionResult Edit (int id) 
        {
            var raw = expensesContext.Expenses.FirstOrDefault(exp => exp.Id == id);
            return View(raw);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {

            var std = expensesContext.Expenses.FirstOrDefault(exp => exp.Id == id);
            if(std == null)
            {
              //  return View("Error");
            }
            var dft = expensesContext.Expenses.Remove(std);
            expensesContext.SaveChanges();
            
             var account = expensesContext.accounts.FirstOrDefault(e => e.Id == std.AccountId);
            if (account != null)
            {
                account.Amount = account.Amount + std.Amount;
                expensesContext.SaveChanges();
            }
            return Redirect("/Expenses");
        }
                
    }
}

ExpenceManagement/Views/Expenses/Create.cshtml
@model ExpenceManagement.Models.ExpenseModel

@{
    ViewBag.Title = "Create";
}

<script>
    function ValidedExpenses() {
        var cat = document.getElementById("CategoryId").value;
        if (cat === "0") {
            alert("Enter category Id")
            return false;
        }
    
         var Acc = document.getElementById("AccountId").value;
        if(Acc === "0"){
            alert("Enter Account Id")
            return false;
        }
  
        var dat = document.getElementById("date").value;
        if(dat.length === 0){
            alert("Select Date")
            return false;
        }
    
        var det = document.getElementById("Details").value;
        if(det.length === 0){
            alert("Enter Details")
            return false;
        }
          var rem = document.getElementById("Remarks").value;
        if(rem.length === 0){
            alert("Enter Remark")
            return false;
        }
         var amt = document.getElementById("Amount").value;
        if (amt === "0") {
            alert("Enter Your Item Amount")
            return false;
        }
        return true;
    }
</script>




<div style="font-family:Arial">
    <h2>Create</h2>

    @using (Html.BeginForm(method: FormMethod.Post))
    {
        @Html.ValidationSummary(true)


        <fieldset>
            <div class="row">
                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Expenses.CategoryId)
                    </div>
                    <div class="editor-field">
                        <select name="Expenses.CategoryId" id="CategoryId" class="form-control">
                            @{
                                <option value="0">Select Account</option>
                                foreach (var cate in Model.Categories)
                                {
                                    <option value="@cate.Id">@cate.CategoryName</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="col-3">
                    <div class="editor-label">
                        <label>AccountId</label>
                    </div>
                    <div class="editor-field">
                        <select name="Expenses.AccountId" id="AccountId" class="form-control">
                            @{
                                <option value="0">Select Category</option>
                                foreach (var cate in Model.Accounts)
                                {
                                    <option value="@cate.Id">@cate.BankName</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                
                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Expenses.Date)
                    </div>
                    <div class="editor-field">
                        <input type="date" name="Expenses.date" value="@Model.Expenses.Date" id="date" placeholder="Select Date" class="form-control">
                        @Html.ValidationMessageFor(Model => Model.Expenses.Date)
                    </div>
                </div>


                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Expenses.Details)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(Model => Model.Expenses.Details, new { @class="form-control", id="Details" ,placeholder="Enter Details"})
                        @Html.ValidationMessageFor(Model => Model.Expenses.Details)
                    </div>
                </div>


                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Expenses.Remarks)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(Model => Model.Expenses.Remarks, new { @class="form-control",id="Remarks", placeholder="Enter Remarks"})
                        @Html.ValidationMessageFor(Model => Model.Expenses.Remarks)
                    </div>
                </div>


                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Expenses.Amount)
                    </div>
                    <div class="editor-field">
                        <input type="number" name="Expenses.Amount" value="@Model.Expenses.Amount" id="Amount" placeholder="Enter Amount" class="form-control"/>
                        @Html.ValidationMessageFor(Model => Model.Expenses.Amount)
                    </div>
                </div>
               <div class="col-3" style="padding-top:22px">
                    <input type="submit" value="Create" class="btn btn-success" onclick="return ValidedExpenses()"/>
                    <input type="submit" value="Create" class="btn btn-outline-success" />
               </div>
            </div>

        </fieldset>

    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExpenceManagement/Views/Expenses/Delete.cshtml
@model ExpenceManagement.Models.Expenses

@{
    ViewBag.Title = "Delete";
}

<div style="font-family:Arial">
    <h2>Delete</h2>


</div>

ExpenceManagement/Views/Expenses/Details.cshtml
 @model ExpenceManagement.Models.Expenses

@{
    ViewBag.Title = "Expenses Details";
}

<h2>Expenses Details</h2>

<table style="font-family:Arial">
    <tr>
        <td>
            <b>AccountId:</b>
        </td>
        <td>
            @Model.Account?.BankName
        </td>
    </tr>
    <tr>
        <td>
            <b>CategoryId:</b>
        </td>
        <td>
            @Model.Category?.CategoryName
        </td>
    </tr>
    <tr>
        <td>
            <b>Id:</b>
        </td>
        <td>
            @Model.Id
        </td>
    </tr>
    <tr>
        <td>
            <b>Date:</b>
        </td>
        <td>
            @Model.Date
        </td>
    </tr>
     <tr>
        <td>
            <b>Details:</b>
        </td>
        <td>
            @Model.Details
        </td>
    </tr>
     <tr>
        <td>
            <b>Remarks:</b>
        </td>
        <td>
            @Model.Remarks
        </td>
    </tr>
    <tr>
        <td>
            <b>Amount:</b>
        </td>
        <td>
            @Model.Amount
        </td>
    </tr>
     
</table>
<form method="post" action="/expenses/delete/@Model.Id">
    <input type="hidden" name="Id" value="@Model.Id" />
    <input type="submit" value="Delete" onclick="return confirm('Are you sure to delete amount @Model.Amount?')" />
</form>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExpenceManagement/Views/Expenses/Edit.cshtml
@model ExpenceManagement.Models.Expenses

@{
    ViewBag.Title = "Edit";
}

<div style="font-family:Arial">
    <h2>Expenses Edit</h2>

    @using (Html.BeginForm(method: FormMethod.Post))
    {
        @Html.ValidationSummary(true)


        <fieldset>
            <div class="row">
                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Id)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(Model => Model.Id, new { @class="form-control" })
                        @Html.ValidationMessageFor(Model => Model.Id)
                    </div>
                </div>

                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Date)
                    </div>
                    <div class="editor-field">
                        <input type="datetime" name="date" class="form-control" value="@Model.Date.ToString("dd-MMM-yyyy")" />
                        @Html.ValidationMessageFor(Model => Model.Date)
                    </div>
                </div>

                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Details)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(Model => Model.Details, new {@class="form-control"})
                        @Html.ValidationMessageFor(Model => Model.Details)
                    </div>
                </div>

                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Remarks)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(Model => Model.Remarks, new {@class="form-control"})
                        @Html.ValidationMessageFor(Model => Model.Remarks)
                    </div>
                </div>

                <div class="col-3">
                    <div class="editor-label">
                        @Html.LabelFor(Model => Model.Amount)
                    </div>
                    <div class="editor-field">
                        <input type="number" name="Amount" class="form-control" value="@Model.Amount" />
                        @Html.ValidationMessageFor(Model => Model.Amount)
                    </div>
                </div>

                <div class="col-3" style="padding-top:22px">
                    <input type="submit" value="Update" class="btn btn-outline-success"/>
                </div>
            </div>
        </fieldset>

    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExpenceManagement/Views/Expenses/Index.cshtml
 @model List<ExpenceManagement.Models.Expenses>





 @{
    ViewBag.Title = "Expenses List";
}
<style>
    .first {
        background-color: palevioletred;
        color: black;
        border: 4px solid green;
    }

    h2 {
        text-align: center;
        background-color: red;
        color: black;
    }
</style>
<div class="first">

    <h2>Expenses List</h2>
    <div class="row">
        <div class="col-3" style="padding:22px">
            @Html.ActionLink("Add Expenses" ,"Create")
        </div>

         <Form class="col-3" style="padding:10px" class="form-control">
            @using (Html.BeginForm("Index", "Expenses", FormMethod.Get))
            {
                <b>Search by</b> @Html.RadioButton("searchby", "Details", true)<b>Details</b>
                @Html.RadioButton("searchby", "Remarks")<b>Remarks</b><br />
                @Html.TextBox("search") <button type="submit" value="Search" class="btn btn-primary">Search</button/>
            }
        </Form>
    </div>

    <table border="1" class="table">
        <tr>
            <th>Id</th>
            <th>Date</th>
            <th>Details</th>
            <th>Remarks</th>
            <th>Amount</th>
            <th>CategoryName</th>
            <th>BankName</th>
            <th>Action Item</th>

        </tr>

        @foreach (var item in Model)
        {
            @using (Html.BeginForm("Delete", "Expenses", new { id = item.Id }, FormMethod.Post))
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Date</td>
                    <td>@item.Details</td>
                    <td>@item.Remarks</td>
                    <td>@item.Amount</td>
                    <td>@item.Category?.CategoryName</td>
                    <td>@item.Account?.BankName</td>
                    <td>
                        @Html.ActionLink("Edit","Edit", new {id=item.Id})
                        @Html.ActionLink("Details","Details",new {id=item.Id})
                    </td>
                </tr>
            }
        }

        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td style="text-align:right">
                Total Amount :
            </td>
            <td>
                @Model.Sum(e=>e.Amount)
            </td>
        </tr>
    </table>
</div>